services:
  shellysim:
    image: shellysim:latest
    container_name: shellysim
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      MQTT_HOST: "${MQTT_HOST:-192.168.1.10}"
      MQTT_PORT: "${MQTT_PORT:-1883}"
      MQTT_TOPIC_IN: "${MQTT_TOPIC_IN:-shellysim/cmnd/apower}"
      HTTP_PORT: "${HTTP_PORT:-80}"
      MQTT_CLIENT: "${MQTT_CLIENT:-shellysim}"
      MQTT_USER: "${MQTT_USER}"
      MQTT_PASS: "${MQTT_PASS}"
